apiVersion: v1
kind: Pod
metadata:
  name: blueapp-pod
  labels:	
    app: blueapp-label
spec:
  containers:
    - name: blueapp-container
      image: cloudmanly/eks:blueapp
      ports:
        - containerPort: 8080