---
kind: Pod
apiVersion: v1
metadata:
  name: blueapp-pod
  labels:
    app: blueapp
spec:
  containers:
    - name: blueapp
      image: cloudmanly/eks:blueapp
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blueapp-svc
spec:
  selector:
    app: blueapp
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: LoadBalancer # classic load balancer service...