---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storage-name
provisioner: ebs.csi.aws.com 
parameters:
  type: standard
  encrypted: 'true'
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storage-name
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-app
spec:
  containers:
  - name: blueapp
    image: cloudmanly/eks:blueapp
    ports:
      - containerPort: 8080
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim