apiVersion: v1
kind: PersistentVolume
metadata:
name: example-persistent-volume
spec:
storageClassName: standard
capacity:
storage: 10Gi
volumeMode: Filesystem
accessModes:
- ReadWriteMany
persistentVolumeReclaimPolicy: Retain
nfs:
server: 172.10.1.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: example-persistent-volume-claim
spec:
storageClassName: standard
resources:
requests:
storage: 500Mi
volumeMode: Filesystem
accessModes:
- ReadWriteMany
selector:
matchLabels:
environment: "prod"

---
apiVersion: v1
kind: Pod
metadata:
name: pod-pvc-as-volume
spec:
containers:
- image: nginx
name: nginx-application
volumeMounts:
- mountPath: /data/application
name: example-storage
volumes:
- name: example-storage
persistentVolumeClaim:
claimName: example-claim