apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  storageClassName: gp2
  capacity:
     storage: 5Gi
  volumeMode: Filesystem
  accessModes:
     - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.5.92
    path: /mnt/nfs_share/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  storageClassName: gp2
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
       environment: "dev"
---
kind: Pod
apiVersion: v1
metadata:
  name: blueapp-nfs
spec:
  containers:
  - name: blueapp
    image: cloudmanly/eks:blueapp
    ports:
      - containerPort: 8080
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
   - name: persistent-storage
     persistentVolumeClaim:
       claimName: nfs-pvc