apiVersion: v1
kind: Secret
metadata:
  name: top-secret
data:
  username: Ym9i
  password: c3VwZXItc2VjcmV0
---
apiVersion: v1
kind: Pod
metadata:
  name: blueapp
spec:
  volumes:
    - name: empty-volume
      emptyDir: {}
    - name: secret-vol
      secret:
        secretName: top-secret
  containers:
    - name: blueapp
      image: cloudmanly/eks:blueapp
      ports:
        - containerPort: 8080
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]  
      volumeMounts:
        - name: empty-volume     # 🔧 match this name
          mountPath: /data
        - name: secret-vol
          readOnly: true
          mountPath: /opt/tomcat/secret-vol
